// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: languages.sql

package database

import (
	"context"
)

const createLanguage = `-- name: CreateLanguage :one
INSERT INTO languages (id, created_at, updated_at, name)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1
)
RETURNING id, created_at, updated_at, name
`

func (q *Queries) CreateLanguage(ctx context.Context, name string) (Language, error) {
	row := q.db.QueryRowContext(ctx, createLanguage, name)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getLanguage = `-- name: GetLanguage :one
SELECT id, created_at, updated_at, name FROM languages
WHERE LOWER(name) = $1
`

func (q *Queries) GetLanguage(ctx context.Context, name string) (Language, error) {
	row := q.db.QueryRowContext(ctx, getLanguage, name)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
